export const products = [
  {
    id: 1,
    title: "Luxury Watch",
    price: 1200,
    image: "/neww.avif",
    category: "Watch",
  },
  {
    id: 2,
    title: "Gold Chain",
    price: 800,
    image: "/lc.avif",
    category: "Chain",
  },
  {
    id: 3,
    title: "Designer Sunglasses",
    price: 450,
    image: "/pg.avif",
    category: "Glasses",
  },
  {
    id: 4,
    title: "Designer Ring",
    price: 450,
    image: "/newr.avif",
    category: "Ring",
  },
  {
    id: 5,
    title: "Luxury Watch ffjvh",
    price: 1200,
    image: "/neww.avif",
    category: "Watch",
  },
  {
    id: 6,
    title: "Gold Chain hhcg",
    price: 800,
    image: "/lc.avif",
    category: "Chain",
  },
  {
    id: 7,
    title: "Designer Sunglasses yu",
    price: 450,
    image: "/ls.avif",
    category: "Glasses",
  },
  {
    id: 8,
    title: "Designer Ring===",
    price: 450,
    image: "/lw.avif",
    category: "Ring",
  },
  {
    id: 9,
    title: "Luxury Watch ffjvh",
    price: 1200,
    image: "/neww.avif",
    category: "Watch",
  },
  {
    id: 10,
    title: "Gold Chain hhcg",
    price: 800,
    image: "/lc.avif",
    category: "Chain",
  },
  {
    id: 11,
    title: "Designer Sunglasses yu",
    price: 450,
    image: "/ls.avif",
    category: "Glasses",
  },
  {
    id: 12,
    title: "Designer Ring===",
    price: 450,
    image: "/lw.avif",
    category: "Ring",
  },
];
